In [1]:
import os
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

challenge_root = '.'
!cat {challenge_root}/README.md

NEU surface defect challenge
hippolyta:/mnt/data/users/holmlab/datasets/neu-challenge

The Northeastern University (NEU) surface defect dataset contains six kinds of typical surface defects found on hot-rolled steel strip: rolled-in scale (RS), patches (Pa), crazing (Cr), pitted surface (PS), inclusion (In) and scratches (Sc).
The dataset consists of 1,800 grayscale images: 300 samples for each surface defect class.

The NEU challenge task is to tune and train a surface defect classifier.
During the challenge you will have access to a training set of 1200 images (200 per defect class) and their labels, as well as the 600 test images (no labels).
Submissions will consist of your final predictions on the test set, along with your code and any analysis you choose to do.

Feel free to use any classifier of your choice, but please refrain from using any deep learning frameworks for this challenge.
As we saw in our workshop session, ImageNet embedding features and even small-ish ConvNets mak

In [3]:
import os
import numpy as np
# import matplotlib.pyplot as plt

challenge_root = '.'


def load_neu(np_path):
    """ load images and labels from numpy binary file """
    with np.load(np_path) as data:

        images = data['images']

        # test datafile doesn't contain labels
        # just return the images
        try:
            labels = data['labels']
        except KeyError:
            return images

        return images, labels

training_datafile = os.path.join(challenge_root, 'train.npz')
X_train, labels_train = load_neu(training_datafile)

test_datafile = os.path.join(challenge_root, 'test.npz')
Xtest = load_neu(test_datafile)


def preprocess_raw(images):
    """ flatten images into raw pixel vectors """
    n = images.shape[0]
    X = images.reshape((n, -1))
    return X.astype(np.float32)


N = 1200
initial_shuf = np.random.permutation(N)
X = X_train[initial_shuf]
y = labels_train[initial_shuf]


In [ ]:
# SVM with LibSVM solver

from sklearn.cross_validation import cross_val_score
from sklearn.svm import SVC
from sklearn import cross_validation

C = [1e-10， 1e-8, 1e-6, 1e-4, 1e-2]
Gamma = ['auto']
Kernel = ['linear', 'rbf','poly', 'sigmoid']
Degree = [2, 3, 4, 5]

Xtrain = preprocess_raw(X)

for k in Kernel:
    for c in C:
        for g in Gamma:
            if k == 'poly':
                for d in Degree:
                    model = SVC(C=c, kernel=k, gamma=g, degree=d,
                                verbose=False, cache_size=1000)
                    metric = cross_val_score(
                        model, Xtrain, y, cv=6, scoring='accuracy')
                    print('Parameters:', 'C = {}'.format(c),
                          ', Kernel = {}'.format(k),
                          ', Gamma = {}'.format(g),
                          ', Degree = {}'.format(d))
                    avg = np.mean(metric)
                    print(metric)
                    print('Average = {}'.format(avg))
            else:
                model = SVC(C=c, kernel=k, gamma=g,
                            verbose=False, cache_size=1000)
                metric = cross_val_score(
                    model, Xtrain, y, cv=6, scoring='accuracy')
                print('Parameters:', 'C = {}'.format(c),
                      ', Kernel = {}'.format(k),
                      ', Gamma = {}'.format(g))
                avg = np.mean(metric)
                print(metric)
                print('Average = {}'.format(avg))

### Large Scale Search Results:

    
    Linear
    Parameters: C = 1e-10 , Kernel = linear , Gamma = auto
    [ 0.33823529  0.38235294  0.35353535  0.32828283  0.33333333  0.31818182]
    Average = 0.34232026143790845
    Parameters: C = 1e-08 , Kernel = linear , Gamma = auto
    [ 0.52941176  0.49019608  0.53030303  0.51515152  0.51515152  0.57070707]
    Average = 0.5251534957417311
    Parameters: C = 1e-06 , Kernel = linear , Gamma = auto
    [ 0.45098039  0.41666667  0.45454545  0.43434343  0.45454545  0.43939394]
    Average = 0.44174589027530203
    Parameters: C = 0.0001 , Kernel = linear , Gamma = auto
    [ 0.43137255  0.41176471  0.43434343  0.41414141  0.42424242  0.43434343]
    Average = 0.42503466032877796
    Parameters: C = 0.01 , Kernel = linear , Gamma = auto
    [ 0.43137255  0.41176471  0.43434343  0.41414141  0.42424242  0.43434343]
    Average = 0.42503466032877796
    
---

    RBF
    Parameters: C = 1e-10 , Kernel = rbf , Gamma = auto
    [ 0.37254902  0.35294118  0.39393939  0.42929293  0.4040404   0.34848485]
    Average = 0.3835412953060012
    Parameters: C = 1e-08 , Kernel = rbf , Gamma = auto
    [ 0.37745098  0.45098039  0.35353535  0.38383838  0.36363636  0.37878788]
    Average = 0.38470489205783326
    Parameters: C = 1e-06 , Kernel = rbf , Gamma = auto
    [ 0.4754902   0.46078431  0.42929293  0.43434343  0.37878788  0.43939394]
    Average = 0.43634878193701726
    Parameters: C = 0.0001 , Kernel = rbf , Gamma = auto
    [ 0.4754902   0.46078431  0.42929293  0.43434343  0.37878788  0.43939394]
    Average = 0.43634878193701726
    Parameters: C = 0.01 , Kernel = rbf , Gamma = auto
    [ 0.4754902   0.46078431  0.42929293  0.43434343  0.37878788  0.43939394]
    Average = 0.43634878193701726
    
---
    
    Poly
    Parameters: C = 1e-10 , Kernel = poly , Gamma = auto , Degree = 2
	[ 0.39705882  0.35294118  0.38383838  0.39393939  0.38888889  0.34343434]
	Average = 0.3766835016835017
    Parameters: C = 1e-08 , Kernel = poly , Gamma = auto , Degree = 2
    [ 0.46568627  0.46078431  0.48989899  0.5         0.47979798  0.52525253]
    Average = 0.48690334719746486
    Parameters: C = 1e-06 , Kernel = poly , Gamma = auto , Degree = 2
    [ 0.55882353  0.49509804  0.51010101  0.53030303  0.47979798  0.48484848]
    Average = 0.509828678946326
    Parameters: C = 0.0001 , Kernel = poly , Gamma = auto , Degree = 2
    [ 0.5245098   0.48039216  0.48989899  0.50505051  0.44949495  0.46464646]
    Average = 0.4856654783125371
    Parameters: C = 0.01 , Kernel = poly , Gamma = auto , Degree = 2
    [ 0.5245098   0.48039216  0.48989899  0.50505051  0.44949495  0.46464646]
    Average = 0.4856654783125371
    
    Parameters: C = 1e-10 , Kernel = poly , Gamma = auto , Degree = 3
	[ 0.47058824  0.49019608  0.51010101  0.52020202  0.5         0.48484848]
	Average = 0.49598930481283426
    Parameters: C = 1e-08 , Kernel = poly , Gamma = auto , Degree = 3
    [ 0.50490196  0.49509804  0.46969697  0.52525253  0.45959596  0.44444444]
    Average = 0.48316498316498313
    Parameters: C = 1e-06 , Kernel = poly , Gamma = auto , Degree = 3
    [ 0.5         0.49509804  0.46969697  0.52525253  0.45959596  0.44444444]
    Average = 0.48234798970093085
    Parameters: C = 0.0001 , Kernel = poly , Gamma = auto , Degree = 3
    [ 0.5         0.49509804  0.46969697  0.52525253  0.45959596  0.44444444]
    Average = 0.48234798970093085
    Parameters: C = 0.01 , Kernel = poly , Gamma = auto , Degree = 3
    [ 0.5         0.49509804  0.46969697  0.52525253  0.45959596  0.44444444]
    Average = 0.48234798970093085
    
    Parameters: C = 1e-10 , Kernel = poly , Gamma = auto , Degree = 4
	[ 0.44117647  0.48039216  0.5         0.48484848  0.47979798  0.45454545]
	Average = 0.47346009110715
    Parameters: C = 1e-08 , Kernel = poly , Gamma = auto , Degree = 4
    [ 0.48529412  0.47058824  0.45454545  0.50505051  0.44444444  0.3989899 ]
    Average = 0.45981877599524656
    Parameters: C = 1e-06 , Kernel = poly , Gamma = auto , Degree = 4
    [ 0.48529412  0.47058824  0.45454545  0.50505051  0.44444444  0.3989899 ]
    Average = 0.45981877599524656
    Parameters: C = 0.0001 , Kernel = poly , Gamma = auto , Degree = 4
    [ 0.48529412  0.47058824  0.45454545  0.50505051  0.44444444  0.3989899 ]
    Average = 0.45981877599524656
    Parameters: C = 0.01 , Kernel = poly , Gamma = auto , Degree = 4
    [ 0.48529412  0.47058824  0.45454545  0.50505051  0.44444444  0.3989899 ]
    Average = 0.45981877599524656
    
    Parameters: C = 1e-10 , Kernel = poly , Gamma = auto , Degree = 5
    [ 0.38235294  0.45588235  0.48989899  0.47474747  0.45454545  0.42929293]
	Average = 0.44778669043374925
    Parameters: C = 1e-08 , Kernel = poly , Gamma = auto , Degree = 5
    [ 0.5245098   0.42156863  0.46969697  0.41414141  0.43434343  0.42424242]
    Average = 0.4480837789661319
    Parameters: C = 1e-06 , Kernel = poly , Gamma = auto , Degree = 5
    [ 0.5245098   0.42156863  0.46969697  0.41414141  0.43434343  0.42424242]
    Average = 0.4480837789661319
    Parameters: C = 0.0001 , Kernel = poly , Gamma = auto , Degree = 5
    [ 0.5245098   0.42156863  0.46969697  0.41414141  0.43434343  0.42424242]
    Average = 0.4480837789661319
    Parameters: C = 0.01 , Kernel = poly , Gamma = auto , Degree = 5
    [ 0.5245098   0.42156863  0.46969697  0.41414141  0.43434343  0.42424242]
    Average = 0.4480837789661319
    
---
    
    Sigmoid
    
    Parameters: C = 1e-10 , Kernel = sigmoid , Gamma = auto
    [ 0.16666667  0.16666667  0.16666667  0.16666667  0.16666667  0.16666667]
    Average = 0.16666666666666666
    Parameters: C = 1e-08 , Kernel = sigmoid , Gamma = auto
    [ 0.16666667  0.16666667  0.16666667  0.16666667  0.16666667  0.16666667]
    Average = 0.16666666666666666
    Parameters: C = 1e-06 , Kernel = sigmoid , Gamma = auto
    [ 0.16666667  0.16666667  0.16666667  0.16666667  0.16666667  0.16666667]
    Average = 0.16666666666666666    
    Parameters: C = 0.0001 , Kernel = sigmoid , Gamma = auto
    [ 0.16666667  0.16666667  0.16666667  0.16666667  0.16666667  0.16666667]
    Average = 0.16666666666666666    
    Parameters: C = 0.01 , Kernel = sigmoid , Gamma = auto
    [ 0.16666667  0.16666667  0.16666667  0.16666667  0.16666667  0.16666667]
    Average = 0.16666666666666666

---

### Smaller Scale Search


	Linear:
	
	1st search: (1e-09,1e-06)
	Parameters: C = 1e-09 , Kernel = linear , Gamma = auto
	[ 0.46078431  0.39215686  0.40909091  0.43434343  0.37878788  0.33333333]
	Average = 0.40141612200435733
	Parameters: C = 5e-09 , Kernel = linear , Gamma = auto
	[ 0.49509804  0.48039216  0.45454545  0.52020202  0.49494949  0.42424242]
	Average = 0.4782382650029709
	Parameters: C = 1e-08 , Kernel = linear , Gamma = auto
	[ 0.60294118  0.51470588  0.46969697  0.55050505  0.51010101  0.45959596]
	Average = 0.5179243414537532
	Parameters: C = 5e-08 , Kernel = linear , Gamma = auto
	[ 0.58823529  0.55392157  0.53030303  0.54040404  0.56060606  0.47979798]
	Average = 0.5422113289760347
	Parameters: C = 1e-07 , Kernel = linear , Gamma = auto
	[ 0.56372549  0.50980392  0.54545455  0.55050505  0.54040404  0.5       ]
	Average = 0.5349821746880571
	Parameters: C = 5e-07 , Kernel = linear , Gamma = auto
	[ 0.48039216  0.42156863  0.46969697  0.45454545  0.49494949  0.43939394]
	Average = 0.4600911071499307
	Parameters: C = 1e-06 , Kernel = linear , Gamma = auto
	[ 0.44607843  0.43137255  0.43939394  0.41414141  0.47979798  0.4040404 ]
	Average = 0.43580411962764903
	
	
	2nd search: (1e-08,1e-07)
	Parameters: C = 1e-08 , Kernel = linear , Gamma = auto
	[ 0.5245098   0.4754902   0.56060606  0.53535354  0.53535354  0.50505051]
	Average = 0.5227272727272728
	Parameters: C = 2e-08 , Kernel = linear , Gamma = auto
	[ 0.54411765  0.48039216  0.58585859  0.56060606  0.61111111  0.54545455]
	Average = 0.5545900178253119
	Parameters: C = 3e-08 , Kernel = linear , Gamma = auto
	[ 0.55392157  0.46568627  0.5959596   0.57575758  0.6010101   0.55050505]
	Average = 0.557140027728263
	Parameters: C = 4e-08 , Kernel = linear , Gamma = auto
	[ 0.54901961  0.45588235  0.61616162  0.57575758  0.62121212  0.54545455]
	Average = 0.5605813032283621
	Parameters: C = 5e-08 , Kernel = linear , Gamma = auto
	[ 0.55882353  0.46078431  0.61111111  0.58585859  0.61111111  0.55050505]
	Average = 0.5630322836205189
	Parameters: C = 6e-08 , Kernel = linear , Gamma = auto
	[ 0.54411765  0.46078431  0.61616162  0.58585859  0.61616162  0.53535354]
	Average = 0.5597395523866112
	Parameters: C = 7e-08 , Kernel = linear , Gamma = auto
	[ 0.53431373  0.48039216  0.62626263  0.57070707  0.6010101   0.53535354]
	Average = 0.5580065359477125
	Parameters: C = 8e-08 , Kernel = linear , Gamma = auto
	[ 0.53921569  0.48039216  0.62121212  0.56565657  0.6010101   0.55050505]
	Average = 0.5596652802535156
	Parameters: C = 9e-08 , Kernel = linear , Gamma = auto
	[ 0.52941176  0.48039216  0.6010101   0.55555556  0.61111111  0.54040404]
	Average = 0.5529807882749059
	Parameters: C = 1e-07 , Kernel = linear , Gamma = auto
	[ 0.50980392  0.47058824  0.58585859  0.55555556  0.5959596   0.52525253]
	Average = 0.5405030699148345
	
	
	
	3rd search: (4e-08, 6e-08)
	Parameters: C = 4e-08 , Kernel = linear , Gamma = auto
	[ 0.53921569  0.57843137  0.58080808  0.52020202  0.55050505  0.55555556]
	Average = 0.5541196276490394
	Parameters: C = 4.2e-08 , Kernel = linear , Gamma = auto
	[ 0.53431373  0.57843137  0.58080808  0.52020202  0.55555556  0.56060606]
	Average = 0.5549861358684889
	Parameters: C = 4.4e-08 , Kernel = linear , Gamma = auto
	[ 0.53921569  0.57352941  0.58080808  0.53030303  0.55555556  0.56060606]
	Average = 0.5566696375519905
	Parameters: C = 4.6e-08 , Kernel = linear , Gamma = auto
	[ 0.53921569  0.57352941  0.58080808  0.53030303  0.56060606  0.56565657]
	Average = 0.5583531392354922
	Parameters: C = 4.8e-08 , Kernel = linear , Gamma = auto
	[ 0.53431373  0.57352941  0.57575758  0.53030303  0.56565657  0.57070707]
	Average = 0.5583778966131908
	Parameters: C = 5e-08 , Kernel = linear , Gamma = auto
	[ 0.53431373  0.57352941  0.57070707  0.51515152  0.57070707  0.57070707]
	Average = 0.5558526440879383
	Parameters: C = 5.2e-08 , Kernel = linear , Gamma = auto
	[ 0.53431373  0.56862745  0.57575758  0.51515152  0.56060606  0.57070707]
	Average = 0.5541938997821351
	Parameters: C = 5.4e-08 , Kernel = linear , Gamma = auto
	[ 0.52941176  0.56372549  0.57070707  0.51515152  0.56060606  0.57070707]
	Average = 0.5517181620122797
	Parameters: C = 5.6e-08 , Kernel = linear , Gamma = auto
	[ 0.53431373  0.56862745  0.57070707  0.51515152  0.56060606  0.57070707]
	Average = 0.5533521489403843
	Parameters: C = 5.8e-08 , Kernel = linear , Gamma = auto
	[ 0.52941176  0.56862745  0.56565657  0.51010101  0.56060606  0.56565657]
	Average = 0.5500099029510794

Linear result:

$C\in(4.6\times10^{-8}, 4.8\times 10^{-8})$

---

	RBF:
	Parameters: C = 1e-08 , Kernel = rbf , Gamma = auto
	[ 0.37254902  0.42156863  0.33838384  0.40909091  0.36363636  0.43939394]
	Average = 0.39077044959397905
	Parameters: C = 5e-08 , Kernel = rbf , Gamma = auto
	[ 0.37254902  0.44607843  0.42929293  0.40909091  0.41919192  0.46464646]
	Average = 0.423474945533769
	Parameters: C = 1e-07 , Kernel = rbf , Gamma = auto
	[ 0.44117647  0.44607843  0.42929293  0.40909091  0.41919192  0.46464646]
	Average = 0.4349128540305011
	Parameters: C = 5e-07 , Kernel = rbf , Gamma = auto
	[ 0.44607843  0.44607843  0.42929293  0.43939394  0.41919192  0.46464646]
	Average = 0.44078035254505843
	Parameters: C = 1e-06 , Kernel = rbf , Gamma = auto
	[ 0.44607843  0.44607843  0.42929293  0.43939394  0.41919192  0.46464646]
	Average = 0.44078035254505843
	
RBF result:

Less than 50%, not in consideration

---

	Poly:
	Degree=2: 
	1st search(1e-8, 1e-6)
	Parameters: C = 1e-08 , Kernel = poly , Gamma = auto , Degree = 2
	[ 0.49019608  0.51470588  0.52020202  0.43939394  0.47979798  0.49494949]
	Average = 0.4898742325212913
	Parameters: C = 5e-08 , Kernel = poly , Gamma = auto , Degree = 2
	[ 0.59313725  0.59313725  0.57575758  0.58585859  0.57070707  0.58080808]
	Average = 0.5832343038225393
	Parameters: C = 1e-07 , Kernel = poly , Gamma = auto , Degree = 2
	[ 0.60784314  0.58333333  0.58080808  0.58080808  0.57070707  0.58080808]
	Average = 0.5840512972865913
	Parameters: C = 5e-07 , Kernel = poly , Gamma = auto , Degree = 2
	[ 0.56862745  0.57843137  0.51515152  0.48484848  0.53030303  0.51010101]
	Average = 0.5312438106555754
	Parameters: C = 1e-06 , Kernel = poly , Gamma = auto , Degree = 2
	[ 0.55392157  0.53921569  0.46464646  0.52525253  0.51010101  0.50505051]
	Average = 0.5163646266587444
	
	2nd search(5e-8, 15e-8)
	Parameters: C = 5e-08 , Kernel = poly , Gamma = auto , Degree = 2
	[ 0.62745098  0.58333333  0.57070707  0.55050505  0.58585859  0.51515152]
	Average = 0.5721677559912853
	Parameters: C = 7.5e-08 , Kernel = poly , Gamma = auto , Degree = 2
	[ 0.64215686  0.59313725  0.55555556  0.56565657  0.55050505  0.52020202]
	Average = 0.5712022182610418
	Parameters: C = 1e-07 , Kernel = poly , Gamma = auto , Degree = 2
	[ 0.66666667  0.6127451   0.56060606  0.55555556  0.53535354  0.53535354]
	Average = 0.5777134085957615
	Parameters: C = 1.25e-07 , Kernel = poly , Gamma = auto , Degree = 2
	[ 0.64705882  0.59803922  0.57070707  0.56565657  0.53030303  0.53535354]
	Average = 0.5745197068726481
	Parameters: C = 1.5e-07 , Kernel = poly , Gamma = auto , Degree = 2
	[ 0.6372549   0.6127451   0.58080808  0.56060606  0.50505051  0.52525253]
	Average = 0.5702861952861954
	
	Degree=3:
	1st search(1e-12, 1e-10)
	Parameters: C = 1e-12 , Kernel = poly , Gamma = auto , Degree = 3
	[ 0.52941176  0.5         0.51010101  0.52020202  0.56565657  0.59090909]
	Average = 0.5360467419290948
	Parameters: C = 5e-12 , Kernel = poly , Gamma = auto , Degree = 3
	[ 0.55392157  0.57843137  0.47474747  0.55555556  0.59090909  0.52525253]
	Average = 0.5464695979401862
	Parameters: C = 1e-11 , Kernel = poly , Gamma = auto , Degree = 3
	[ 0.53431373  0.53921569  0.45454545  0.54040404  0.53030303  0.47979798]
	Average = 0.5130966528025351
	Parameters: C = 3e-11 , Kernel = poly , Gamma = auto , Degree = 3
	[ 0.50980392  0.51470588  0.45959596  0.52525253  0.47979798  0.49494949]
	Average = 0.49735096058625466
	Parameters: C = 6e-11 , Kernel = poly , Gamma = auto , Degree = 3
	[ 0.5         0.50490196  0.44949495  0.52525253  0.50505051  0.48989899]
	Average = 0.49576648841354726
	Parameters: C = 1e-10 , Kernel = poly , Gamma = auto , Degree = 3
	[ 0.50490196  0.53921569  0.42929293  0.52525253  0.51010101  0.5       ]
	Average = 0.5014606852842146
	
	2nd search(1e-12, 1e-11)
	Parameters: C = 1e-12 , Kernel = poly , Gamma = auto , Degree = 3
	[ 0.57843137  0.55392157  0.50505051  0.51515152  0.51010101  0.5       ]
	Average = 0.5271093285799168
	Parameters: C = 2e-12 , Kernel = poly , Gamma = auto , Degree = 3
	[ 0.60294118  0.58333333  0.51515152  0.56565657  0.58080808  0.5       ]
	Average = 0.5579817785700139
	Parameters: C = 3e-12 , Kernel = poly , Gamma = auto , Degree = 3
	[ 0.60294118  0.57843137  0.52525253  0.54545455  0.58585859  0.51010101]
	Average = 0.5580065359477124
	Parameters: C = 4e-12 , Kernel = poly , Gamma = auto , Degree = 3
	[ 0.59803922  0.54901961  0.51515152  0.56060606  0.58080808  0.48484848]
	Average = 0.5480788274905922
	Parameters: C = 5e-12 , Kernel = poly , Gamma = auto , Degree = 3
	[ 0.57843137  0.55882353  0.51515152  0.53535354  0.58080808  0.49494949]
	Average = 0.5439195880372351
	Parameters: C = 6e-12 , Kernel = poly , Gamma = auto , Degree = 3
	[ 0.56372549  0.54901961  0.54040404  0.53535354  0.56060606  0.48484848]
	Average = 0.5389928698752228
	

	
	
	
Degree=2 result:

$C \in(5\times 10^{-8}, 1.5\times 10^{-7})$

Degree=3 result:

$C \in (1\times 10^{-12}, 1\times 10^{-11})$

### Output prediction

In [ ]:
# Linear model:

from sklearn.svm import SVC
model = SVC(C=4.7e-8, kernel='linear', verbose=True, cache_size=1000)

X = preprocess_raw(X_train)
%time model.fit(X, labels_train)

score = model.score(X, labels_train)
print('training acc: {}'.format(score))

# test_datafile = os.path.join('..', 'test.npz')
# Xtest, ltest = load_neu(test_datafile)
# print('test acc: {}'.format(
#     model.score(preprocess_raw(Xtest), ltest)
#     )
# )
y_pred=model.predict(preprocess_raw(Xtest))
np.save('predict_linear.npy', y_pred)

[LibSVM]

In [ ]:
# Poly(degree=2) model:

from sklearn.svm import SVC
model = SVC(C=1e-7, kernel='poly', degree=2, verbose=True, cache_size=1000)

X = preprocess_raw(X_train)
%time model.fit(X, labels_train)

score = model.score(X, labels_train)
print('training acc: {}'.format(score))

# test_datafile = os.path.join('..', 'test.npz')
# Xtest, ltest = load_neu(test_datafile)
# print('test acc: {}'.format(
#     model.score(preprocess_raw(Xtest), ltest)
#     )
# )
y_pred=model.predict(preprocess_raw(Xtest))
np.save('predict_linear.npy', y_pred)

In [ ]:
# Poly(degree=3) model:

from sklearn.svm import SVC
model = SVC(C=3e-12, kernel='poly', degree=2, verbose=True, cache_size=1000)

X = preprocess_raw(X_train)
%time model.fit(X, labels_train)

score = model.score(X, labels_train)
print('training acc: {}'.format(score))

# test_datafile = os.path.join('..', 'test.npz')
# Xtest, ltest = load_neu(test_datafile)
# print('test acc: {}'.format(
#     model.score(preprocess_raw(Xtest), ltest)
#     )
# )
y_pred=model.predict(preprocess_raw(Xtest))
np.save('predict_linear.npy', y_pred)